name: Security and Linting for Maven
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  security-and-lint:
    runs-on: ubuntu-latest
    steps:
      # Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para GitGuardian y Super-Linter

      # Configurar Java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Ajusta según tu proyecto
          distribution: 'temurin'

      # Snyk: Escanear dependencias
      - name: Snyk Dependency Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npm install -g snyk
          snyk auth $SNYK_TOKEN
          snyk test --file=pom.xml
        continue-on-error: true

      # Snyk: Escanear código
      - name: Snyk Code Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test
        continue-on-error: true

      # GitGuardian: Escanear secretos
      - name: GitGuardian Scan
        uses: GitGuardian/ggshield-action@v1
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

      # Super-Linter: Validar Java y Kotlin
      - name: Super-Linter
        uses: super-linter/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVA: true
          VALIDATE_KOTLIN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: '.*(target|node_modules).*'
          JAVA_FILE_NAME: checkstyle.xml
